// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("index.html", "Untitled Page", "untitled page seguridad informática sede nacional josé celestino mutis calle sur no pbx bogotá colombialínea gratuita desde colombia atención al usuario atencionalusuario unad edu coanticorrupción anticorrupcion co sawgrass corporate parkway suite sunrise fl phones toll free fax Última actualización copyright nbsp powered by jwysiwyg el curso en le brinda un amplio conocimiento práctica real equipos con las más actuales herramientas técnicas de ataque defensa permitiendo consecuentemente actuar criterio sobre la materia enfoque práctico está basado distintos tipos ataques diversos entornos usted obtendrá los conocimientos teóricos una visión estratégica aplicación practica cuales profesionales especializados trabajan campo bajo altos niveles complejidad nivel internacional contenidos estarán constante correlación estándares internacionales metodologia perfil profesional egresado del programa especialización estará capacidad ser capaz aplicar promover metodologías actualizadas que conduzcan cultura diseñar estrategias puedan garantizar recursos informáticos tal forma se convierta valor agregado procesos negocio entre cliente empresa nacionales aspectos éticos legales rigen especialista desempeñarse como analista diseñador administrador implementador sistemas políticas normatividad organizaciones públicas privadas regional noticias página principal eventos log in user name password remember me páginas interés ", "");
   this[database_length++] = new SearchPage("lecturas.html", "Untitled Page", "untitled page ataques informáticos delitos consejos de seguridad informática sede nacional josé celestino mutis calle sur no pbx bogotá colombialínea gratuita desde colombia atención al usuario atencionalusuario unad edu coanticorrupción anticorrupcion co sawgrass corporate parkway suite sunrise fl phones toll free fax Última actualización copyright nbsp powered by jwysiwyg noticias página principal eventos log in user name password remember me páginas interés lecturas ", "");
   this[database_length++] = new SearchPage("ataquesinfor.html", "Untitled Page", "untitled page un ataque informático consiste en aprovechar alguna debilidad falla vulnerabilidad el software hardware incluso las personas que forman parte de ambiente fin obtener beneficio por lo general índole económico causando efectos negativos la seguridad del sistema luego repercute directamente los activos organización para minimizar impacto negativo provocado ataques existen procedimientos mejores prácticas facilitan lucha contra actividades delictivas reducen notablemente campo acción uno pasos más importantes es educación comprender cuáles son debilidades comunes pueden ser aprovechadas sus riesgos asociados permitirá conocer qué manera se ataca ayudando identificar desplegar inteligente estrategias efectivas información sede nacional josé celestino mutis calle sur no pbx bogotá colombialínea gratuita desde colombia atención al usuario atencionalusuario unad edu coanticorrupción anticorrupcion co sawgrass corporate parkway suite sunrise fl phones toll free fax Última actualización copyright nbsp powered by jwysiwyg noticias página principal eventos log in user name password remember me páginas interés ataqueinformático ", "");
   this[database_length++] = new SearchPage("delitosinfor.html", "Untitled Page", "untitled page los delitos informáticos son aquellas actividades ilícitas que se cometen mediante el uso de computadoras sistemas otros dispositivos comunicación la informática es medio instrumento para realizar un delito tienen por objeto causar daños provocar pérdidas impedir también conocidos como ciberdelitos lo señala téllez actitudes contrarias intereses las personas en tiene fin concepto atípico conductas atípicas antijurídicas culpables típico julio derecho informático ed mcgraw hill méxico u7mucha información almacenada reducido espacio con una posibilidad recuperación inmediata pero complejas sean medidas seguridad puedan implantar aún no existe método infalible protección más sede nacional josé celestino mutis calle sur pbx bogotá colombialínea gratuita desde colombia atención al usuario atencionalusuario unad edu coanticorrupción anticorrupcion co sawgrass corporate parkway suite sunrise fl phones toll free fax Última actualización copyright nbsp powered by jwysiwyg noticias página principal eventos log in user name password remember me páginas interés delitosinformáticos ", "");
   this[database_length++] = new SearchPage("consejos.html", "Untitled Page", "untitled page instalar utilizar mantener actualizados anti virus spyware en todos los equipos utilizados la empresa garantizar seguridad de conexión internet actualizado cortafuegos software ordenadores pequeña revisar al día parches actualizaciones sistemas operativos aplicaciones proveedores ofrecen sus productos para corregir problemas mejorar funcionalidad hacer copias datos empresariales importantes es necesario realizar porque se quot mueren discos duros fallan empleados cometen errores programas maliciosos pueden destruir controlar el acceso físico componentes red no debe permitir que las personas autorizadas tengan deben extremar precauciones con personal limpieza entra espacio oficina durante noche así como informáticos externos encargados actualizar reparar asegurar punto inalámbrico redes trabajo utilizando contraseñas fuertes sede nacional josé celestino mutis calle sur pbx bogotá colombialínea gratuita desde colombia atención usuario atencionalusuario unad edu coanticorrupción anticorrupcion co sawgrass corporate parkway suite sunrise fl phones toll free fax Última actualización copyright nbsp powered by jwysiwyg noticias página principal eventos log in user name password remember me páginas interés consejos seguridadinformática ", "");
   this[database_length++] = new SearchPage("multimedia.html", "Untitled Page", "untitled page sede nacional josé celestino mutis calle sur no pbx bogotá colombialínea gratuita desde colombia atención al usuario atencionalusuario unad edu coanticorrupción anticorrupcion co sawgrass corporate parkway suite sunrise fl phones toll free fax Última actualización copyright nbsp powered by jwysiwyg noticias página principal eventos log in user name password remember me páginas de interés multimedia ", "");
   this[database_length++] = new SearchPage("actividades.html", "Untitled Page", "untitled page sede nacional josé celestino mutis calle sur no pbx bogotá colombialínea gratuita desde colombia atención al usuario atencionalusuario unad edu coanticorrupción anticorrupcion co sawgrass corporate parkway suite sunrise fl phones toll free fax Última actualización copyright nbsp powered by jwysiwyg noticias página principal eventos log in user name password remember me páginas de interés actividades ", "");
   this[database_length++] = new SearchPage("autores.html", "Untitled Page", "untitled page autores estudiante programa ingeniería de sistemas código skype dflopez12correo dflopezt unadvirtual edu co daniel fernando lópez torres german andres rodriguez jairo andrés urbano german04rodriguez gmail comcorreo garodriguezmo xxxxxxxxskype xxxxxxcorreo jaurbanoga sede nacional josé celestino mutis calle sur no pbx bogotá colombialínea gratuita desde colombia atención al usuario atencionalusuario unad coanticorrupción anticorrupcion sawgrass corporate parkway suite sunrise fl phones toll free fax Última actualización copyright nbsp powered by jwysiwyg noticias página principal eventos log in user name password remember me páginas interés ", "");
   return this;
}
